name: Build LfpLatency on ubuntu
on: 
  push:
    tags:
      - v*
jobs:

  build:
    name: Compile action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: OEPlugins/OE-plugin-latency-tracker
      - name: Checkout
        uses: actions/checkout@v2

        with:
          repository: open-ephys/plugin-GUI
          path: plugin-GUI
      - name: setup env
        working-directory: plugin-GUI/Resources/Scripts
        env:
          CC: gcc-12
          CXX: g++-12
        run: |
          sudo apt-get update
          sudo apt install gcc-12 g++-12
          sudo ./install_linux_dependencies.sh
          cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      - name: Build plugin
        env:
          CC: gcc-12
          CXX: g++-12
        working-directory: OEPlugins/OE-plugin-latency-tracker/Build 
        run: |
          cmake -G "Unix Makefiles" ..
          make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          files: 'OEPlugins/OE-plugin-latency-tracker/Build/*.so'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
