name: Build plugin-gui macos
on: workflow_dispatch

jobs:
  build:
    name: Compile action
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build plugin-gui
        run: |
          cd .. 
          git clone https://github.com/open-ephys/plugin-GUI.git 
          cd plugin-GUI/Build
          cmake -G "Xcode" ..
          xcodebuild -scheme ALL_BUILD build
          cd ../../OE-plugin-latency-tracker/Build
          cmake -G "Xcode" ..
          ls
          xcodebuild -list -project OE_PLUGIN_OE-plugin-latency-tracker.xcodeproj/
          xcodebuild -scheme ALL_BUILD build
      # - name: Archive compiled plugin-gui artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: plugin-GUI
      #     path: |
      #       /home/runner/work/OE-plugin-latency-tracker/plugin-GUI
      # - name: Archive compiled plugin-gui/Build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Build
      #     path: |
      #       /home/runner/work/OE-plugin-latency-tracker/plugin-GUI/Build