name: Build plugin-gui image and push
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Add your dockerhub username to the repo's secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Add your dockerhub password to the repo's secrets
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: merlllle/compiled-plugin-gui:latest # Replace with your username and appname in the format as `username/appname:latest`
          file: ./Containerization/Dockerfile