name: Build LfpLatency on windows
on: 
  workflow_dispatch:
    inputs:
      release_name: 
        description: The name of the release to attach the build artefacts

jobs:

  build:
    name: Compile action
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: OEPlugins/OE-plugin-latency-tracker
     
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: open-ephys/plugin-GUI
          path: plugin-GUI
          ref: v0.5.2.2
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: setup env
        working-directory: plugin-GUI/Build
        run: |   
         cmake -G "Visual Studio 17 2022" -A x64 ..
         curl -L -o oebuild.zip https://github.com/open-ephys/plugin-GUI/releases/download/v0.5.2.2/open-ephys-v0.5.2.2-windows.zip
         7z x oebuild.zip
         mkdir Release
         mv open-ephys/* Release
         
      - name: Build plugin
        working-directory: OEPlugins/OE-plugin-latency-tracker/Build 
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cd ..
          msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64
          
      - name: Release
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          files: 'OEPlugins/OE-plugin-latency-tracker/Build/Release/*.dll'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

