name: Build LfpLatency on osx
on: 
  workflow_dispatch:
    inputs:
      release_name: 
        description: The name of the release to attach the build artefacts

jobs:

  build:
    name: Compile action
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: OEPlugins/OE-plugin-latency-tracker
     
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: open-ephys/plugin-GUI
          path: plugin-GUI
          ref: v0.5.2.2
      - name: build oe
        working-directory: plugin-GUI
        run: | 
          mkdir -p Build
          cd Build
          cmake ..
          cmake --build . --config Release --target open-ephys -j 2
      - name: build plugin
        working-directory: OEPlugins/OE-plugin-latency-tracker
        run: |
          mkdir -p Build
          cd Build
          cmake ..
          cmake --build . --config Release
      - name: testing
        working-directory: OEPlugins/OE-plugin-latency-tracker/Build
        run : |
          ls -la
      - name: Release
        working-directory: OEPlugins/OE-plugin-latency-tracker/Build
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          files: '*.bundle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
