name: Build LfpLatency without_docker
on: 
  workflow_dispatch:
    inputs:
      release_name: 
        description: The name of the release to attach the build artefacts

jobs:

  build:
    name: Compile action
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: OEPlugins/OE-plugin-latency-tracker
      - name: Checkout
        uses: actions/checkout@v2

        with:
          repository: open-ephys/plugin-GUI
          path: plugin-GUI
      - name: setup env
        working-directory: plugin-GUI/Build
        run: |   
          cmake -G "Visual Studio 16 2019" -A x64 ..
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build plugin
        working-directory: OEPlugins/OE-plugin-latency-tracker/Build 
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 ..
          cd ..
          msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64
      - name: Release
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          files: 'OEPlugins/OE-plugin-latency-tracker/Build/*.dll'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

