name: A workflow for compile
on: push

jobs:
  build:
    name: Compile action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: clang --version
      - run: gcc --version
      - run: cmake --version
      - run: make --version